[package]
name = "hap"
version = "0.1.0-beta.1"
authors = ["Elias Wilken <elias@wlkn.io>"]
edition = "2018"
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
documentation = "https://docs.rs/hap"
readme = "README.md"
repository = "https://github.com/ewilken/hap-rs"
license = "MIT/Apache-2.0"
keywords = ["apple", "homekit"]

[dependencies]
aead = "0.2.0"
async-std = "1.5.0"
byteorder = "1.3.4"
bytes = "0.5.4"
chacha20poly1305 = "0.3.3"
ed25519-dalek = { version = "1.0.0-pre.3", features = ["std", "serde"] }
erased-serde = "0.3.10"
eui48 = { version = "0.4.6", features = ["serde"] }
failure = "0.1.6"
futures = "0.3.4"
hyper = "0.13.2"
libmdns = "0.2.4"
log = "0.4.8"
num = "0.2.1"
rand = "0.7.3"
ring = "0.14.6"
serde = { version = "1.0.104", features = ["rc", "derive"] }
serde_json = "1.0.48"
sha2 = "0.8.1"
srp = "0.4.3"
tokio = { version = "0.2.13", features = ["full"] }
url = "2.1.1"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
x25519-dalek = "0.6.0"

[build-dependencies]
handlebars = "2.0.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
uuid = { version = "0.8.1", features = ["v4", "serde"] }

[dev-dependencies]
env_logger = "0.7.1"
pnet = "0.25.0"
